#!/usr/bin/env bash


usage() {
cat << EOF
Valery bot

Fly.io based Valery bot deploy script

Usage:
    ${0} [OPTIONS]

Options:
    --new               Launch new application using fly.toml template
    --app APP           Application name to use for deploy. Overrides one in toml file
    --image             Mongo image to deploy (default: ${MONGO_IMAGE})
    --allocate-ips      Allocate ip addresses on launch
    --debug             Set bash 'x' option
    --help              Show help message

Examples:
    Deploy new app.
    
        ./deploy --new --app mymongo

    Redeploy. 
        
        ./deploy

Note:
    This script allocates shared ipv4 and ipv6 addresses that cost nothing
    Dedicated ipv4 address costs \$2/month
EOF
}

SCRIPT_DIR=$(realpath "$(dirname "${0}")")
MONGO_IMAGE=python:3.11-bookworm

while [ "${#}" -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            exit
            ;;

        --app)
            shift
            APP_NAME="${1}"
            ;;

        --new)
            NEW=1
            ;;

        --image)
            shift
            MONGO_IMAGE="${1}"
            ;;

        --allocate-ips)
            ALLOCATE_IPS=1
            ;;

        --debug)
            set -x
            ;;

        *)
            echo "Unreconginzed argument: ${1}"
            usage
            exit 1
            ;;
    esac
    
   shift
done


if [ -z "$(command -v fly)" ]; then
    curl -L https://fly.io/install.sh | sh
fi 


pushd "${SCRIPT_DIR}" &> /dev/null

set -eEu

on_exit() {
    popd &> /dev/null
}

trap on_exit EXIT

if [ -n "${APP_NAME+x}" ]; then
    FLY_TOML_FN="${SCRIPT_DIR}/fly.toml"
    sed -i "s/app = \".*\"/app = \"${APP_NAME}\"/g" "${FLY_TOML_FN}"
fi

if [ -n "${NEW+x}" ]; then
    yes no | fly launch --copy-config --path /tmp --no-deploy --build-arg "BASE=${MONGO_IMAGE}"

    if [ -n "${ALLOCATE_IPS+x}" ]; then
        fly ips allocate-v4 --shared
        fly ips allocate-v6
    fi
fi

fly deploy --build-arg "BASE=${MONGO_IMAGE}"
