version: "3"

# volumes:
#   valery-data:

services:
  mongo:
    container_name: mongo
    # image: mongo:latest
    build:
      dockerfile: mongo.Dockerfile
    restart: always
    user: mongo:mongo
    volumes:
      # - valery-data:/data/db
      - ${MONGODB_PATH:-./.volumes/mongodb}:/data/db

  valery:
    container_name: valery
    command: /home/valery/app/start.sh --log-level "${VALERY_LOG_LEVEL:-DEBUG}" --deps-log-level "${VALERY_DEPS_LOG_LEVEL:-WARNING}"
    restart: always
    build: "."
    # volumes:
    #   - ${VALERY_CONFIG_PATH:-./.volumes/valery}:/config
    depends_on:
      - mongo
